config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'

  get    '/chat_rooms',              to: 'chat_rooms#index'
  post   '/chat_rooms',              to: 'chat_rooms#create'
  get    '/chat_rooms/:id',          to: 'chat_rooms#room'
  delete '/chat_rooms/:id',          to: 'chat_rooms#destroy'
  post   '/chat_rooms/new',          to: 'chat_rooms#new'
  post   '/chat_rooms/clear',        to: 'chat_rooms#clear'
  post   '/chat_rooms/message',      to: 'chat_rooms#message'
  post   '/chat_rooms/:id/invite',   to: 'chat_rooms#invite'
  post   '/chat_rooms/:id/throwout', to: 'chat_rooms#throwout'

  get    '/users',     to: 'users#index'
  post   '/users',     to: 'users#create'
  get    '/signup',    to: 'users#new'
  get    '/users/:id', to: 'users#show'
  delete '/users/:id', to: 'users#destroy'

  get    '/signin',  to: 'user_sessions#new'
  post   '/signin',  to: 'user_sessions#create'
  delete '/signout', to: 'user_sessions#destroy'

  post '/friend_request',         to: 'friend_ships#friend_request'
  post '/approve_friend_request', to: 'friend_ships#approve'

  get '*path', to: 'application#render_404'
end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  belongs_to :admin_user, class_name: :User
  has_many :participation_permissions, class_name: :ParticipationPermissionToChat, dependent: :destroy
  has_many :joined_users, through: :participation_permissions, source: :user

  def ChatRoom.initialized_chat
    chat = {
      messages: []
    }
  end

  def throwout(user)
    participation_permissions.find_by(user_id: user.id).destroy
  end

  class ChatRoom::Message
    require 'date'
    attr_reader :speaker, :date, :content
    def initialize(content, speaker = 'NANASHI')
      @speaker = speaker
      @date    = DateTime.now
      @content = content
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:room, :destroy, :clear, :message]
  def index
    @rooms = ChatRoom.all
  end

  def new
    @room = ChatRoom.new
  end

  def create
    @room = ChatRoom.new(chat_room_params)
    if signed_in?
      @room.admin_user = current_user
    end
    hash_chat  = ChatRoom.initialized_chat
    @room.chat = hash_chat.to_json
    if @room.save
      redirect_to action: 'room', id: @room.id, notice: 'Chat room was successfully created.'
    else
      render :new
    end
  end

  # like show
  def room
    unless allow_enter_room?
      puts '----------------------------------'
      p params
      puts '----------------------------------'
      redirect_to controller: :application, action: :render_404
      return
    end
    Pusher.url = ENV["PUSHER_URL"]
    @messages = @room.chat['messages']
  end

  def destroy
    @room.destroy
    redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.'
  end

  def clear
    @room.update_attributes(chat: ChatRoom.initialized_chat)
    redirect_to action: 'room', id: @room.id, notice: 'Chat history cleared'
  end

  def message
    render :nothing => true
    message  = ChatRoom::Message.new(params[:data])
    chat = @room.chat
    chat["messages"].push(message)
    @room.chat = chat.to_json
    @room.save
    view_message = {date: message.date, speaker: message.speaker, content: message.content.gsub(/\r\n|\r|\n/, "<br />")}
    Pusher["channel_#{@room.id}"].trigger('chat_event', { message: view_message, id: @room.id })
  end

  def invite
    invited_user = User.find_by(name: params[:search_name])
    room = ChatRoom.find(params[:id])
    if invited_user && !room.joined_users.include?(invited_user)
      permission = ParticipationPermissionToChat.create(user: invited_user, chat_room: room)
      room.participation_permissions.push(permission)
    end
    redirect_to action: :room
  end

  def throwout
    target_user = User.find(params[:target_id])
    room = ChatRoom.find(params[:id])
    if target_user && room.joined_users.include?(target_user)
      room.throwout(target_user)
    end
    redirect_to action: :room
  end

  private
    def set_chat_room
      @room = ChatRoom.find(params[:id])
    end

    def chat_room_params
      params.require(:chat_room).permit(:name, :private)
    end

    def allow_enter_room?
      !@room.private || @room.joined_users.include?(current_user) || (signed_in? && @room.admin_user == current_user) || (signed_in? && current_user.admin)
    end
end

app/views/chat_rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this chat_room from being saved:"
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  - if signed_in?
    .field
      =f.radio_button :private, true
      =f.label :private, :Private
    .field
      =f.radio_button :private, false
      =f.label :private, :Public
  .actions
    = f.submit 'Create'

app/views/chat_rooms/index.html.haml
- if signed_in?
  %h1 Welcome to #{current_user.name}

- if signed_in?
  = button_to 'My page', {controller: :users, action: :show, id: current_user.id}, method: :get
  = button_to 'Sign out', signout_path, method: :delete
- else
  = button_to 'Sign up',  signup_path,  method: :get
  = button_to 'Sign in',  signin_path,  method: :get

%h1 ChatRooms

= button_to 'New Chat Room', chat_rooms_new_path

%table{border: "5"}
  %tr
    %th ID
    %th ROOM NAME
    %th PRIVATE?
    %th ADMIN
  - @rooms.each do |room|
    %tr
      %td= room.id
      %td= room.name
      %td= room.private ? 'PRIVATE' : 'PUBLIC'
      %td= room.admin_user ? room.admin_user.name : 'Nothing'
      - if !room.private || room.joined_users.include?(current_user) || (signed_in? && current_user == room.admin_user) || (signed_in? && current_user.admin)
        %td= link_to 'Enter', {action: 'room', id: room.id}
      - if !room.private || (signed_in? && current_user == room.admin_user) || (signed_in? && current_user.admin)
        %td= link_to 'Destroy', {action: 'destroy', id: room.id}, {data: {method: :delete, confirm: 'Are you sure?'}}

app/views/chat_rooms/new.html.haml
- if signed_in?
  %h1= "Hello #{current_user.name}"
%h2 Create Chat Room

= render 'form'

= link_to 'Back', chat_rooms_path

app/views/chat_rooms/room.html.haml
#data_storage{ data: { 'pusher-key' => Pusher.key, 'room-id' => @room.id } }

%h1= "Welcome to ChatRoom-#{@room.name}"
%h2= "Created by #{@room.admin_user ? @room.admin_user.name : "Unknown User"}"

- if @room.private && @room.admin_user && @room.admin_user == current_user
  = form_tag(action: :invite) do
    .field
      = text_field_tag :search_name, nil, placeholder: 'Search User'
      = submit_tag 'Search'

- if @room.private
  %h3 Joined users
  %h4 Admin : #{@room.admin_user.name}
  %ul
    - @room.joined_users.each do |user|
      %li
        = user.name
        - if @room.admin_user && @room.admin_user == current_user
          = button_to 'Good bye', {action: :throwout, target_id: user.id}

%textarea#text{placeholder: "入力してください", cols: "40", rows: "4"}
%input#post{type: "button", value: "送信"}
= button_to "clear", {action: "clear", id: @room.id}, {confirm: "really?"}
%ul
  - @messages.each do |msg|
    - msg["content"].gsub!(/\r\n|\r|\n/, "<br />")
    %li= "#{msg["date"]} - #{msg["speaker"]}"
    = "#{msg["content"]}"