config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'

  get    '/chat_rooms',              to: 'chat_rooms#index'
  post   '/chat_rooms',              to: 'chat_rooms#create'
  get    '/chat_rooms/:id',          to: 'chat_rooms#room'
  delete '/chat_rooms/:id',          to: 'chat_rooms#destroy'
  post   '/chat_rooms/new',          to: 'chat_rooms#new'
  post   '/chat_rooms/clear',        to: 'chat_rooms#clear'
  post   '/chat_rooms/message',      to: 'chat_rooms#message'
  post   '/chat_rooms/:id/invite',   to: 'chat_rooms#invite'
  post   '/chat_rooms/:id/throwout', to: 'chat_rooms#throwout'

  get    '/users',     to: 'users#index'
  post   '/users',     to: 'users#create'
  get    '/signup',    to: 'users#new'
  get    '/users/:id', to: 'users#show'
  delete '/users/:id', to: 'users#destroy'

  get    '/signin',  to: 'user_sessions#new'
  post   '/signin',  to: 'user_sessions#create'
  delete '/signout', to: 'user_sessions#destroy'

  post '/friend_request',         to: 'friend_ships#friend_request'
  post '/approve_friend_request', to: 'friend_ships#approve'

  get '*path', to: 'application#render_404'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,     presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 4, maximum: 20 }

  has_many :friendships_from_oneself, -> { where(approval: true) }, class_name: :FriendShip, foreign_key: :from_user_id, dependent: :destroy
  has_many :friendships_to_oneself,   -> { where(approval: true) }, class_name: :FriendShip, foreign_key: :to_user_id,   dependent: :destroy
  has_many :pending_friendships_from_oneself, -> { where(approval: false) }, class_name: :FriendShip, foreign_key: :from_user_id, dependent: :destroy
  has_many :pending_friendships_to_oneself,   -> { where(approval: false) }, class_name: :FriendShip, foreign_key: :to_user_id,   dependent: :destroy

  has_many :friends_from_oneself, through: :friendships_from_oneself, source: :to_user
  has_many :friends_to_oneself,   through: :friendships_to_oneself,   source: :from_user
  has_many :pending_friends_from_oneself, through: :pending_friendships_from_oneself, source: :to_user
  has_many :pending_friends_to_oneself,   through: :pending_friendships_to_oneself,   source: :from_user

  has_secure_password

  def friends
    self.friends_from_oneself + self.friends_to_oneself
  end

  def relation(user)
    return 'Friend' if friends.include?(user)
    return 'Send friend request' if self.pending_friends_from_oneself.include?(user)
    return 'Has been requested'  if self.pending_friends_to_oneself.include?(user)
    return 'Oneself' if self == user
    return 'Nothing'
  end

  def has_relation?(user)
    relation(user) != 'Nothing'
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:destroy, :show]
  def index
    unless signed_in? && current_user.admin
      redirect_to controller: :application, action: :render_404
      return
    end
    clear_location
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to controller: :chat_rooms, action: :index
    else
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    if user && user.admin
      redirect_to users_url, notice: 'fail'
      return
    end
    user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed'
  end

  def show
    @user  = User.find(params[:id])
    @users = User.where(admin: false)
    unless current_user?(@user)
      correct_user = current_user
      redirect_to action: :show, id: correct_user.id
      return
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

    def signed_in_user
      store_location
      unless signed_in?
        flash[:warning] = "Please sign in"
        redirect_to signin_url
      end
    end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation, "Confirm Password"
    = f.text_field :password_confirmation
  .actions
    = f.submit 'Create Account'

app/views/users/index.html.haml
%h1 Users ALL

%table{border: "5"}
  %tr
    %th ID
    %th NAME
    %th ADMIN
    %th DELETE
  - @users.each do |user|
    %tr
      %td= user.id
      %td= user.name
      %td= user.admin ? "YES" : "NO"
      - unless user.admin
        %td= button_to 'Delete', {action: 'destroy', id: user.id}, {method: :delete, data: {confirm: 'Are you sure?'}}

app/views/users/new.html.haml
%h1 Please input your name and password

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%h4= link_to 'HOME', users_path, method: :get

%h1 User page
%h2 Welcome #{@user.name}

= button_to 'Sign out', signout_path, method: :delete

%table{border: "2"}
  %tr
    - 6.times do
      %th NAME
      %th RELATION
  - @users.each_with_index do |user, i|
    - if i%6 == 0
      %tr
    %td= user.name
    - relation = @user.relation(user)
    %td
      = button_to 'Friend Request',  {controller: :friend_ships, action: :friend_request, from_id: @user.id, to_id: user.id} if relation == 'Nothing'
      = button_to 'Approve request', {controller: :friend_ships, action: :approve, from_id: user.id, to_id: @user.id}        if relation == 'Has been requested'
      = relation if relation != 'Nothing' && relation != 'Has been requested'

- unless @user.admin?
  = button_to 'Cancel the membership', {action: 'destroy', id: @user.id}, {method: :delete, data: {confirm: 'Are you sure?'}}